name: Build e Publicar Extensão

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Baixar código
        uses: actions/checkout@v3

      - name: 🛠 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Instalar dependências
        run: npm install chrome-webstore-upload node-fetch

      - name: 🔼 Atualizar versão do manifest
        run: node bump-version.js

      - name: 🗜 Criar pacote .zip
        run: zip -r minha-extensao.zip . -x ".git/*" ".github/*" "node_modules/*"

      - name: 🚀 Publicar na Chrome Web Store
        run: node deploy-monitor.js
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          ZIP_FILE: './minha-extensao.zip'
